// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rusoxhwufkvuugnfaqfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1c294aHd1Zmt2dXVnbmZhcWZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTkwNTQsImV4cCI6MjA3MzUzNTA1NH0.BH6pN2H1rgnfMURHj5HD8j3WnNhF0TrHfosjjZ2XVK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});